//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entites
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Configuration;
    using ViewModel;

    public partial class UserDetail
    {
        public int User_ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BranchName { get; set; }
        public int Semester { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public System.DateTime AdmissionDate { get; set; }
       
        public virtual UserAuthentication UserAuthentication { get; set; }




        public static IList<UserDetail> GetUserDetails() {

            SqlConnection Connection = null;
            SqlCommand Command = null;
            SqlDataReader Data = null;

            try
            {
                Connection = new SqlConnection(ConfigurationManager.ConnectionStrings["StudentManagementConnection"].ConnectionString.ToString());
                Connection.Open();
                Command = new SqlCommand("Select * from UserDetails", Connection);
                Data = Command.ExecuteReader();
                var userdetails = new List<UserDetail>();
                while (Data.Read())
                {
                    userdetails.Add(
                        new UserDetail()
                        {
                            User_ID = Data.GetInt16(0),
                            FirstName = Data.GetString(1),
                            MiddleName = Data.GetString(2),
                            LastName = Data.GetString(3),
                            BranchName = Data.GetString(4),
                            Semester = Data.GetInt16(5),
                            Age = Data.GetInt16(6),
                            Gender = Data.GetString(7),
                            Address = Data.GetString(8),
                            AdmissionDate = Data.GetDateTime(9),
                            

                        }
                    );
                }
                return userdetails;

            }
            catch (Exception e) {
                throw e;
            }
            finally
            {
                if (Data!=null)
                {
                    try
                    {
                        Data.Close();
                    }
                    catch (SqlException e) {
                    }
                    
                }
                if (Command != null) {
                    try {
                        Command.Dispose();
                    }
                    catch (SqlException e) {
                    }
                    
                   
                }

                if (Connection != null) {
                    try
                    {
                        Connection.Close();
                    }
                    catch (SqlException e) {
                    }
                    
                    
                }
            }
            

        }

        public static UserDetail GetUserDetail(int studentId) {
            SqlConnection Connection = null;
            SqlCommand Command = null;
            SqlDataReader Data = null;

            try
            {
                Connection = new SqlConnection(ConfigurationManager.ConnectionStrings["StudentManagementConnection"].ConnectionString.ToString());
                Connection.Open();
                Command = new SqlCommand("Select * from UserDetails  where User_ID = @studentId", Connection);
                Command.Parameters.AddWithValue("@studentId", studentId);
                Command.Prepare();
                Data = Command.ExecuteReader();

                if (Data.Read())
                {
                    return new UserDetail()
                    {
                        User_ID = Data.GetInt16(0),
                        FirstName = Data.GetString(1),
                        MiddleName = Data.GetString(2),
                        LastName = Data.GetString(3),
                        BranchName = Data.GetString(4),
                        Semester = Data.GetInt16(5),
                        Age = Data.GetInt16(6),
                        Gender = Data.GetString(7),
                        Address = Data.GetString(8),
                        AdmissionDate = Data.GetDateTime(9),

                    };

                }
                else {
                    return null;
                }
                

            }
            catch (SqlException e)
            {
                throw e;
            }
            finally
            {
                if (Data != null)
                {
                    try
                    {
                        Data.Close();
                    }
                    catch (SqlException e)
                    {
                    }
                }
                if (Command != null)
                {
                    try
                    {
                        Command.Dispose();
                    }
                    catch (SqlException e)
                    {
                    }
                }

                if (Connection != null)
                {
                    try
                    {
                        Connection.Close();
                    }
                    catch (SqlException e)
                    {
                    }
                }
            }

        }

        public static bool AddUserDetails(UserDetailDTO userDetail) {
            SqlConnection Connection = null;
            SqlCommand Command = null;

            try
            {
                Connection = new SqlConnection(ConfigurationManager.ConnectionStrings["StudentManagementConnection"].ConnectionString.ToString());
                
                Connection.Open();
                Command.Connection = Connection;
                Command.CommandText = "insert into UserDetails(FirstName,MiddleName,LastName,BranchName,Semester,Age,Gender,Address,AdmissionDate) values(@firstName,@middleName,@lastName,@branchName,@semester,@age,@gender,@address,@admissionDate)";
                Command.Parameters.AddWithValue("@firstName", userDetail.FirstName);
                Command.Parameters.AddWithValue("@middleName", userDetail.MiddleName);
                Command.Parameters.AddWithValue("@lastName", userDetail.LastName);
                Command.Parameters.AddWithValue("@branchName", userDetail.BranchName);
                Command.Parameters.AddWithValue("@semester", userDetail.Semester);
                Command.Parameters.AddWithValue("@age", userDetail.Age);
                Command.Parameters.AddWithValue("@gender", userDetail.Gender);
                Command.Parameters.AddWithValue("@address", userDetail.Address);
                Command.Parameters.AddWithValue("@admissionDate", userDetail.AdmissionDate.Date);
                Command.Prepare();
                
                Command.ExecuteNonQuery();

                
                return true;


            }
            catch (SqlException e)
            {
                return false;
            }
            finally {
                if (Command != null)
                {
                    try
                    {
                        Command.Dispose();
                    }
                    catch (SqlException e)
                    {
                    }
                }

                if (Connection != null)
                {
                    try
                    {
                        Connection.Close();
                    }
                    catch (SqlException e)
                    {
                    }
                }
            }

        }

        public static bool UpdateUserDetail(UserDetailDTO userDetail) {
            SqlConnection Connection = null;
            SqlCommand Command = null;

            try
            {
                Connection = new SqlConnection(ConfigurationManager.ConnectionStrings["StudentManagementConnection"].ConnectionString.ToString());

                Connection.Open();
                Command.Connection = Connection;
                string CommandString= @"UPDATE UserDetails SET  FirstName = @firstName ,
                                        MiddleName = @middleName,LastName = @ lastName,BranchName = @branchName,
                                        semester = @semester , Age = @age , Gender = @gender , Address = @address ,
                                        AdmissionDate = @admissionDate where User_ID = @userID;";
                Command.CommandText = CommandString;
                Command.Parameters.AddWithValue("@userID",userDetail.User_ID);
                Command.Parameters.AddWithValue("@firstName", userDetail.FirstName);
                Command.Parameters.AddWithValue("@middleName", userDetail.MiddleName);
                Command.Parameters.AddWithValue("@lastName", userDetail.LastName);
                Command.Parameters.AddWithValue("@branchName", userDetail.BranchName);
                Command.Parameters.AddWithValue("@semester", userDetail.Semester);
                Command.Parameters.AddWithValue("@age", userDetail.Age);
                Command.Parameters.AddWithValue("@gender", userDetail.Gender);
                Command.Parameters.AddWithValue("@address", userDetail.Address);
                Command.Parameters.AddWithValue("@admissionDate", userDetail.AdmissionDate.Date);
                Command.Prepare();

                Command.ExecuteNonQuery();


                return true;


            }
            catch (SqlException e)
            {
                return false;
            }
            finally
            {
                if (Command != null)
                {
                    try
                    {
                        Command.Dispose();
                    }
                    catch (SqlException e)
                    {
                    }
                }

                if (Connection != null)
                {
                    try
                    {
                        Connection.Close();
                    }
                    catch (SqlException e)
                    {
                    }
                }
            }


        }

        public static bool DeleteUserDetails(int userId) {

            SqlConnection Connection = null;
            SqlCommand Command = null;

            try
            {
                Connection = new SqlConnection(ConfigurationManager.ConnectionStrings["StudentManagementConnection"].ConnectionString.ToString());

                Connection.Open();
                Command.Connection = Connection;
                Command.CommandText = "delete from UserDetails where User_ID = @userID";
                Command.Parameters.AddWithValue("@userID", userId);
                Command.Prepare();

                Command.ExecuteNonQuery();
                
                return true;
                
            }
            catch (SqlException e)
            {
                return false;
            }
            finally
            {
                if (Command != null)
                {
                    try
                    {
                        Command.Dispose();
                    }
                    catch (SqlException e)
                    {
                    }
                }

                if (Connection != null)
                {
                    try
                    {
                        Connection.Close();
                    }
                    catch (SqlException e)
                    {
                    }
                }
            }

        }

    }
}